// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-mcRgDP_WPi5daBfInFE6DR_5rfMjB7A',
    appId: '1:732327756624:web:ea2f7ac7ff3fa4a9772255',
    messagingSenderId: '732327756624',
    projectId: 'cnmthd-iot',
    authDomain: 'cnmthd-iot.firebaseapp.com',
    databaseURL: 'https://cnmthd-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cnmthd-iot.appspot.com',
    measurementId: 'G-2PG6TH89BZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXbjwlPSR_n_NxGBoDxrjB6CJpOkLzaQA',
    appId: '1:732327756624:android:44bfa8389de3d91f772255',
    messagingSenderId: '732327756624',
    projectId: 'cnmthd-iot',
    databaseURL: 'https://cnmthd-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cnmthd-iot.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU1qXJZuJV0ufBCjQAkLXRbEtHC3fHlKM',
    appId: '1:732327756624:ios:a534db95ff2efc6d772255',
    messagingSenderId: '732327756624',
    projectId: 'cnmthd-iot',
    databaseURL: 'https://cnmthd-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cnmthd-iot.appspot.com',
    iosClientId: '732327756624-469rqev4fpje2ij5mba2d7uplo82hpqv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSmartHome',
  );
}
